name: test
on: [pull_request]
jobs:
  pytest:
    runs-on: docker
    timeout-minutes: 15
    steps:
      - name: Fetch PR code
        run: |
          git clone -q "http://oauth2:${{ github.token }}@skyloft.tailb6874b.ts.net:3000/Yeshey/Bolsa.git" repo
          cd repo
          git fetch -q origin "refs/pull/${{ github.event.number }}/head"
          git checkout -q FETCH_HEAD
      - name: Tests
        run: |
          cd repo
          pip install -q --no-cache-dir -r requirements.txt
          python -m pytest -q